#!bin/bash
# NAME:Andrew Ding
# EMAIL:andrewxding@ucla.edu
# ID:504748356

CC = gcc
CFLAGS = -Wall -Wextra -g -o
.SILENT: 

default:
	$(CC) $(CFLAGS) lab1a lab1a.c 
clean:
	rm -f lab1a lab1a-504748356.tar.gz
dist:
	tar -czvf lab1a-504748356.tar.gz README Makefile lab1a.c
