CREATE TABLE IF NOT EXISTS Movie(id INT PRIMARY KEY, title VARCHAR(100), year INT, rating VARCHAR(10), company VARCHAR(50));

CREATE TABLE IF NOT EXISTS Actor(id INT PRIMARY KEY, last VARCHAR(20), first VARCHAR(20), sex VARCHAR(6), dob DATE, CHECK (dob <= CURRENT_DATE()));
-- CREATE TABLE IF NOT EXISTS Actor(id INT, last VARCHAR(20), first VARCHAR(20), sex VARCHAR(6), dob DATE, PRIMARY KEY(id), CHECK (dob <= CURRENT_DATE());

CREATE TABLE IF NOT EXISTS Director(id INT PRIMARY KEY, last VARCHAR(20), first VARCHAR(20), dob DATE, dod DATE, CHECK (dob <= CURRENT_DATE() AND dod <= CURRENT_DATE() AND (dob <= dod OR dob IS NULL OR dod IS NULL)));
-- CREATE TABLE IF NOT EXISTS Director(id INT PRIMARY KEY, last VARCHAR(20), first VARCHAR(20), dob DATE, dod DATE, CHECK (dob <= dod OR dob IS NULL OR dod IS NULL));

CREATE TABLE IF NOT EXISTS MovieGenre(mid INT, genre VARCHAR(20), FOREIGN KEY (mid) REFERENCES Movie(id));

CREATE TABLE IF NOT EXISTS MovieDirector(mid INT, did INT, FOREIGN KEY(mid) REFERENCES Movie(id), FOREIGN KEY(did) REFERENCES Director(id));

CREATE TABLE IF NOT EXISTS MovieActor(mid INT, aid INT, role VARCHAR(50), FOREIGN KEY(mid) REFERENCES Movie(id), FOREIGN KEY(aid) REFERENCES Actor(id));

CREATE TABLE IF NOT EXISTS Review(name VARCHAR(20), time TIMESTAMP, mid INT, rating INT CHECK (0 <= rating AND rating <= 5), comment VARCHAR(500), FOREIGN KEY (mid) REFERENCES Movie(id));

CREATE TABLE IF NOT EXISTS MaxPersonID(id INT);

CREATE TABLE IF NOT EXISTS MaxMovieID(id INT);